### ISSUE TITLE
4.0.0 is not considered a PMMP release at the moment

### ISSUE THREAD

**Issue by kevinishawesome** [thebigsmileXD/Overvoltage#2]
4.0.0 API isn’t considered as usable for anything, it’s not even in the releases yet, please drop support to 3.x.x . So people can use this plugin and test it out

**Comment by inxomnyaa** [comment]
4.0.0 was introduced to change from BaseLang to Language, right @salmonde?

In this plugin it is intended to run on 4.0.0

**Comment by kevinishawesome** [comment]
![a29484ac-cffb-4180-a1b7-c618a8563bc7](https://user-images.githubusercontent.com/36453870/47802998-4ede0f80-dd53-11e8-9aae-5b5ed94fa2ff.jpeg)

@thebigsmileXD

**Comment by SalmonDE** [comment]
@kevinishawesome those are the release versions but this plugin is using the current development version 4.0.0.

**Comment by dktapps** [comment]
> 4.0.0 was introduced to change from BaseLang to Language

no. 4.0 was introduced prior to this, immediately after 3.0 release. All breaking changes go here. As rightly said above, it's currently still under development (as it tells you when you start the server) and not ready for production usage. It's still months from release.

If I bumped the major version to immediate release for every class change we'd be on version 7000 or so by now. 4.0.0 is a package update which is currently incomplete.

**Comment by SOF3** [comment]
4.0.0 isn't released, and this plugin hasn't been released either, so there is no problem. But we can foresee that @thebigsmilexd might have to wait for months before this plugin can get released.

**Comment by inxomnyaa** [comment]
There is no plan on releasing this plugin to i.e. Poggit.

Its a plugin heavily under development.

Also, as you might have noticed from my current repo changes, i bumped many plugins to allow 4.0.0 to be used (for developers)

Locking due to overheat
