### ISSUE TITLE
Server Stopping

### ISSUE THREAD

**Issue by DenielWorld** [thebigsmileXD/Overvoltage#3]
After the server restarts it disables every plugin, and then never starts up until manual restart. This started appearing after installing Overvoltage so that is most likely the problem.

**Comment by inxomnyaa** [comment]
Any console outputs/logs? Without i cannot help

**Comment by DenielWorld** [comment]
I am experimenting with it right now. It might of been a personal problem. Ill let you know when I figure if it is.

**Comment by DenielWorld** [comment]
It seems like the issue I submitted is incorrect. I will close this issue now. I will continue to experiment with redstone and I will submit all the bugs I can find in a different issue.
